name: Android APK Build

on:
  push:
    branches: [ "main" ] # Main dalına kod gönderildiğinde çalışır

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo Kodlarını Çek
      uses: actions/checkout@v3

    - name: Java (JDK 17) Kurulumu
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle Yetkisi Ver
      run: chmod +x gradlew

    - name: APK Derleme (Build)
      run: ./gradlew assembleDebug

    - name: APK Dosyasını Yükle / Çıktı Ver
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
